# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Install any needed packages specified in requirements.txt
# The requirements.txt needs to be prepared with all the necessary libraries.
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Run training script when the container launches
CMD ["python", "./training/horror_movies_training.py"]

# ENTRYPOINT ["tail", "-f", "/dev/null"]
